### ISSUE TITLE
Avoid corrupting date/time values in JVM corruptions (if possible) / Common java.time.DateTimeException crashes when corrupting JVM

### ISSUE THREAD

**Issue by infinitephantasm** [juanmuscaria/a-mod-made-to-corrupt-a-well-known-block-game#2]
corrupting any DateTime value generally leads to an instant crash via a java.time.DateTimeException crash.

such as:
`[Render thread/ERROR] [net.minecraft.client.main.Main/]: Unhandled game exception
java.time.DateTimeException: Field DayOfMonth cannot be printed as the value -110 exceeds the maximum print width of 2`

this happens with other fields, but DayOfMonth is exceedingly common to be corrupted for one reason or another.
i'm unsure if it is possible to exclude or otherwise ignore these values when corrupting, but it would be nice if they could be excluded, to keep potentially good corruptions going on for far longer.

**Comment by juanmuscaria** [comment]
Runtime corruption scrambles the JVM primitive cache, so numbers like 1 can become any random number, you can't really filter how the numbers are really used.

**Comment by infinitephantasm** [comment]
i had a feeling that was the case, but wasn't entirely sure myself. i appreciate the information regardless!
